const ERROR_LOGIN_PASSWORD_INVALID = 'ERROR_LOGIN_PASSWORD_INVALID';
const ERROR_USER_NOT_VERIFICATION = 'ERROR_USER_NOT_VERIFICATION';

export {
    ERROR_LOGIN_PASSWORD_INVALID,
    ERROR_USER_NOT_VERIFICATION,
};
